version: '2.9'

services:
  server:
    build:
      context: ./server
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
  database:
    image: 'postgres'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: