version: '2.9'

services:
  # server:
  #   build:
  #     context: ./backend
  #     dockerfile: 'Dockerfile'
  #   ports:
  #     - '3000:3000'
  database:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: